// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGPZFSUtZpntdquJZIQskBwejM3xiZNjk',
    appId: '1:699909749861:web:2af5b6570b9fc0c4609a8c',
    messagingSenderId: '699909749861',
    projectId: 'elderreg',
    authDomain: 'elderreg.firebaseapp.com',
    storageBucket: 'elderreg.appspot.com',
    measurementId: 'G-69W813PR92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ZqQC0YiKriBwSNxbkF9ahmiTHOeZBQc',
    appId: '1:699909749861:android:46d0fb6d17e61568609a8c',
    messagingSenderId: '699909749861',
    projectId: 'elderreg',
    storageBucket: 'elderreg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_A6wJbkyeQeFz6hiXe_2z9R6q6oAKryk',
    appId: '1:699909749861:ios:bc0c4e2fa54f7cd2609a8c',
    messagingSenderId: '699909749861',
    projectId: 'elderreg',
    storageBucket: 'elderreg.appspot.com',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_A6wJbkyeQeFz6hiXe_2z9R6q6oAKryk',
    appId: '1:699909749861:ios:2dfd05bc77bf0cdf609a8c',
    messagingSenderId: '699909749861',
    projectId: 'elderreg',
    storageBucket: 'elderreg.appspot.com',
    iosBundleId: 'com.example.registration.RunnerTests',
  );
}
